services:
  db:
    image: postgres:13
    container_name: 'db'
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '80:80'
    networks:
      - my_network
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  server:
    image: node:20
    container_name: 'server'
    stdin_open: true
    tty: true
    env_file: .env
    working_dir: /api
    volumes:
      - .:/api

    ports:
      - '${PORT}:${INTERNAL_PORT}'
    depends_on:
      - db
    networks:
      - my_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  my_network:
    driver: bridge
